### ISSUE TITLE
Evidence of accurate predictions

### ISSUE THREAD

**Issue by MrHash** [mrc-ide/covid-sim#176] opened 2020-05-07 17:15 UTC
Responding to the prematurely locked issue https://github.com/mrc-ide/covid-sim/issues/174, i provide citations as requested by your most accomplished developers.

In case you are not familiar with what a [BBOM](https://en.wikipedia.org/wiki/Big_ball_of_mud) is, I provide the definition to which this project clearly fits, and naturally this is embarrassing as expressed by even an Imperial College freshman [here](https://github.com/mrc-ide/covid-sim/issues/163). Perhaps this is not embarrassing to others but expertise in code takes time to develop without creating [Code Smell](https://en.wikipedia.org/wiki/Code_smell).

Now regarding the impact on society that these models have had we can see from the track record as follows:

In 2001, these models led to the slaughter of 6m farm animals.
In 2002, predicted up to 50,000 people would die from BSE. 177 died.
In 2005, estimated bird would kill 200m people. 282 died.
In 2009, estimated swine flu would kill 60,000. 457 died.
In 2020, these models have been off by many orders of magnitude again.

My question is, is there any evidence for predictions that these models have made which were accurate? Please provide citations.

**Comment by beewenib** [comment] 2020-05-07 17:30
This might be duplicate of bug https://github.com/mrc-ide/covid-sim/issues/175 that I've already logged. Unfortunately, I'm not sure they're interested in fixing my bug as it has been closed.

**Comment by MrHash** [comment] 2020-05-07 17:38
Reliable statistical models require backtesting fitness. If this model doesn't, which apparently it doesn't in the real world, then i'd like to know what synthetic history it does actually fit and why that should be the basis of future real world predictions.

**Comment by weshinsley** [comment] 2020-05-07 17:51
(1) This model code did not exist for the 2001, 2002 and 2005 runs you cite. What are these numbers you are actually citing? (2) Read to the bottom of #175; the UK deaths are very much real, and already more than Report 9 suggested as a best case, so whether #175 is as hilarious a bug as you suggest is open to debate.

I am keeping our issue list clean so we can see what we are doing - namely, genuine code-related issues we can work together on, with those who are already exploring the model and its use. If your issues are more philosophical, there are other email addresses you can find on the Imperial College pages which are more appropriate. Please contact those so we can get back to doing our jobs.

**Closed by weshinsley** 2020-05-07 17:51 UTC
