### ISSUE TITLE
Release the Original Source Code or Start Blocking

### ISSUE THREAD

**Issue by rittersb** [mrc-ide/covid-sim#199] opened 2020-05-09 20:16 UTC
@weshinsley You need to either release the original source code which it seems is what the majority of people in the open source community want (Gauging this from the thumbs up and down) or you need to start blocking people. I find it interesting that the infamous CODE_OF_CONDUCT.md is in here yet you are not enforcing it. Most of these discussions boil down into pointless ranting and name calling. You say you won't release it first because you don't have time in #144 (This doesn't make sense. You already have it.), and then you say you won't release it because the community is toxic in #179 (I am not sure how it is toxic by wanting the original code that was used in the report). I will be the first to say that I am no epidemiologist, but what I see from this repository is not conducive to the open source spirit nor is it conducive to version control by squashing your commits.

**Comment by Feynstein** [comment] 2020-05-09 20:26
@rittersb @weshinsley can't help you at all, he can't even merge pull requests. This is a duplicate of #179. Also, this is a very inaproppriate threat you are making.

**Comment by sylaxofficial** [comment] 2020-05-09 20:28
you are a troll 🤔

**Comment by Feynstein** [comment] 2020-05-09 20:31
@sylaxofficial or maybe I just enjoy doing that?

**Comment by Feynstein** [comment] 2020-05-09 20:39
@sylaxofficial by the way I would qualify your shitposting as trolling also... So yeah

**Comment by bbolker** [comment] 2020-05-09 21:53
The tone of the issue is very weird, but I agree that it might save the developers a lot of time and grief at this point if, rather than locking issues,  they started blocking people who are consistently making unconstructive comments https://help.github.com/en/github/building-a-strong-community/blocking-a-user-from-your-organization

**Comment by Feynstein** [comment] 2020-05-09 22:09
@bbolker Is there a way to setup community issue moderating? That way some people that don't necessarily have admin rights for code could at least moderate the issues.

**Comment by weshinsley** [comment] 2020-05-10 08:27
Blocking begun, as requested.
The rest is duplicate of #179 I suppose.

**Closed by weshinsley** 2020-05-10 08:27 UTC
